# Generated by Django 5.1.1 on 2025-03-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_user_alter_review_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, default='user', max_length=100, null=True),
        ),
    ]
