# Generated by Django 5.1.1 on 2025-04-04 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_user_unique_email_user_unique_username'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_email',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_username',
        ),
    ]
